# Generated by Django 5.1.3 on 2024-11-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=200, verbose_name='Make')),
                ('modelis', models.CharField(max_length=200, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pavadinimas', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('Kaina', models.CharField(max_length=200, verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valstybinis_NR', models.CharField(max_length=200, verbose_name='Valstybinis_NR')),
                ('VIN_kodas', models.CharField(max_length=200, verbose_name='VIN_kodas')),
                ('Klientas', models.CharField(max_length=200, verbose_name='Klientas')),
                ('Automobilio_modelis_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='Date')),
                ('automobilis_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kiekis', models.CharField(max_length=200, verbose_name='Kiekis')),
                ('Paslauga_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.paslauga')),
                ('Uzsakymas_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.uzsakymas')),
            ],
        ),
    ]
